name: Build ResourcePack

on:
  push:
    paths:
      - "resourcepack/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip resourcepack
        run: |
          cd resourcepack
          zip -r ../PlasmaCore-ResourcePack.zip .

      - name: Upload ResourcePack
        uses: actions/upload-artifact@v4
        with:
          name: PlasmaCore-ResourcePack
          path: PlasmaCore-ResourcePack.zip
          
